import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    position: "relative",
    alignItems: "center",
    backgroundColor: "#ecf0f1",
    justifyContent: "center",
  },
  fillFormHeader: {
    width,
    height: height / 6,
    backgroundColor: "black",
    opacity: 0.5,
    position: "absolute",
    top: 0,
    left: 0,
    zIndex: 998,
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingBottom: 32,
    flexDirection: "row",
    paddingHorizontal: 12,
  },
  title: {
    fontSize: 32,
    color: "white",
  },
  video: {
    alignSelf: "center",
    flex: 1,
    width: "100%",
    height: "100%",
  },
  close: {
    zIndex: 999,
    alignSelf: "flex-end",
  },
  answerButton: {
    width: width - 80,
    height: 52,
    position: "absolute",
    bottom: height / 18,
    backgroundColor: "green",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 16,
    zIndex: 10000,
  },
  answerText: {
    fontSize: 28,
    color: "white",
  },
  videoUploadingText: {
    color: "white",
    fontSize: 18,
    width: "40%",
    marginTop: 16,
    textAlign: "center",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "#ecf0f1",
    alignItems: "center",
    zIndex: 0,
  },
  userInfoModal: {
    position: "absolute",
    width: width - 80,
    top: height / 2.5,
    alignSelf: "center",
    zIndex: 1001,
    backgroundColor: "gray",
    padding: 24,
    borderRadius: 16,
  },
  userInfoModalInput: {
    borderWidth: 2,
    width: "100%",
    height: 45,
    paddingLeft: 20,
    marginTop: 10,
    borderColor: "#C8CEED",
    borderRadius: 5,
    marginBottom: 16,
  },
  userInfoModalButton: {
    width: "100%",
    height: 52,
    backgroundColor: "green",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 16,
  },
  userInfoModalButtonText: {
    fontSize: 20,
    color: "white",
  },
  userInfoModalText: {
    fontSize: 20,
    color: "white",
  },
  modalCloseIcon: {
    position: "absolute",
    top: 12,
    right: 12,
  },
});
