import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    position: "relative",
  },
  video: {
    alignSelf: "center",
    flex: 1,
    width,
    height,
  },
  buttonsContainer: {
    position: "absolute",
    width: "100%",
    bottom: 20,
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  button: {
    width: width / 3 - 20,
    backgroundColor: "#04092D",
    height: width / 3 - 20,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
    flexDirection: "column-reverse",
  },
  doneButton: {
    backgroundColor: "green",
    borderRadius: 24,
    padding: 4,
  },
  buttonText: {
    fontSize: 20,
    color: "white",
    marginTop: 8,
    textAlign: "center",
    fontWeight: "bold",
  },
  textContainer: {
    marginBottom: 15,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#04092D",
    borderRadius: 12,
    minHeight: 50,
    height: "auto",
    width: 300,
    position: "absolute",
    bottom: 20,
    alignSelf: "center",
    paddingHorizontal: 10,
    paddingVertical: 5,
    justifyContent: "space-between",
  },
  choiceTextInput: {
    marginLeft: 10,
    color: "white",
    textAlign: "center",
    justifyContent: "center",
    fontSize: 20,
    width: "80%",
  },
  choiceContainer: {
    padding: 10,
    alignSelf: "center",
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#04092D",
    borderRadius: 35,
    height: 50,
    width: 330,
    marginHorizontal: 30,
  },
  playButton: {
    position: "absolute",
    top: height / 2 - 40,
    left: width / 2 - 40,
  },
  choiceList: {
    alignSelf: "center",
    width: width - 40,
    position: "absolute",
    bottom: 20,
  },
  choiceIndex: {
    fontSize: 20,
    fontWeight: "bold",
    color: "gray",
    marginLeft: 10,
  },
  choiceText: {
    color: "white",
    textAlign: "center",
    justifyContent: "center",
    fontSize: 18,
    width: "100%",
    fontWeight: "500",
  },
});
